
spring:
  profiles: test
  datasource:
    driver-class-name: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: jdbc:mysql://localhost:3306/usel?useSSL=false  
    username: root 
    password: root  

  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
 
    
  
