-- MySQL Script generated by MySQL Workbench
-- Fri Aug 10 09:45:38 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema usel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema usel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `usel` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `usel` ;

-- -----------------------------------------------------
-- Table `usel`.`Purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usel`.`Purchases` (
  `po` INT NOT NULL AUTO_INCREMENT,
  `final_po_number` INT NULL,
  `user_id` INT NOT NULL,
  `job_id` INT NOT NULL,
  `vendor_id` INT NOT NULL,
  `createdAt` TINYINT NULL,
  `updatedAt` TINYINT NULL,
  PRIMARY KEY (`po`, `user_id`, `job_id`, `vendor_id`));


-- -----------------------------------------------------
-- Table `usel`.`Jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usel`.`Jobs` (
  `job_id` INT NOT NULL,
  `description` VARCHAR(120) NOT NULL,
  `due_date` DATE NOT NULL,
  `m_s_sale` VARCHAR(20) NOT NULL,
  `status` TINYINT NOT NULL,
  `customer_id` INT NOT NULL,
  `createdAt` TINYINT NULL,
  `updatedAt` TINYINT NULL,
  `po_id` INT NOT NULL,
  PRIMARY KEY (`job_id`, `customer_id`),
  INDEX `po_id_idx` (`po_id` ASC),
  CONSTRAINT `po_id`
    FOREIGN KEY (`po_id`)
    REFERENCES `usel`.`Purchases` (`po`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `usel`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usel`.`Customers` (
  `customer_id` INT NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `customer_po` VARCHAR(30) NOT NULL,
  `createdAt` TINYINT NULL,
  `updatedAt` TINYINT NULL,
  `vessel_id` INT NOT NULL,
  `job_id` INT NOT NULL,
  PRIMARY KEY (`customer_id`, `vessel_id`),
  INDEX `job_id_idx` (`job_id` ASC),
  CONSTRAINT `job_id`
    FOREIGN KEY (`job_id`)
    REFERENCES `usel`.`Jobs` (`job_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `usel`.`Vendors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usel`.`Vendors` (
  `vendor_id` INT NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `createdAt` TINYINT NULL,
  `updatedAt` TINYINT NULL,
  `po_id` INT NOT NULL,
  PRIMARY KEY (`vendor_id`),
  INDEX `po_id_idx` (`po_id` ASC),
  CONSTRAINT `po_id`
    FOREIGN KEY (`po_id`)
    REFERENCES `usel`.`Purchases` (`po`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `usel`.`Vessels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usel`.`Vessels` (
  `vessel_id` INT NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  `createdAt` TINYINT NULL,
  `updatedAt` TINYINT NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`vessel_id`),
  INDEX `customer_id_idx` (`customer_id` ASC),
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `usel`.`Customers` (`customer_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `usel`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usel`.`Users` (
  `user_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `short_name` VARCHAR(3) NULL,
  `isEnabled` TINYINT NULL,
  `createdAt` TINYINT NULL,
  `updatedAt` TINYINT NULL,
  `po_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `po_id_idx` (`po_id` ASC),
  CONSTRAINT `po_id`
    FOREIGN KEY (`po_id`)
    REFERENCES `usel`.`Purchases` (`po`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS; 