-- MySQL Script generated by MySQL Workbench
-- Tue Aug  7 11:25:18 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema usel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema usel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `usel` DEFAULT CHARACTER SET utf8 ;
USE `usel` ;

-- -----------------------------------------------------
-- Table `usel`.`Jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usel`.`Jobs` (
  `job_id` INT NOT NULL,
  `description` VARCHAR(120) NOT NULL,
  `customer_id` INT NOT NULL,
  `vessel_id` INT NOT NULL,
  `customer_po` VARCHAR(30) NOT NULL,
  `due_date` DATE NOT NULL,
  `m_s_sale` VARCHAR(20) NOT NULL,
  `status` TINYINT NOT NULL,
  `createdAt` TINYINT NULL,
  `updatedAt` TINYINT NULL,
  PRIMARY KEY (`job_id`, `customer_id`, `vessel_id`));


-- -----------------------------------------------------
-- Table `usel`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usel`.`Customers` (
  `id` INT NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `vessel_id` INT NOT NULL,
  `createdAt` TINYINT NULL,
  `updatedAt` TINYINT NULL,
  PRIMARY KEY (`id`, `vessel_id`),
  CONSTRAINT `fk_Customers_Jobs1`
    FOREIGN KEY (`id`)
    REFERENCES `usel`.`Jobs` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `usel`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usel`.`Users` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `short_name` VARCHAR(3) NULL,
  `isEnabled` TINYINT NULL,
  `createdAt` TINYINT NULL,
  `updatedAt` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usel`.`Purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usel`.`Purchases` (
  `user_id` INT NOT NULL,
  `job_id` INT NOT NULL,
  `po` INT NOT NULL AUTO_INCREMENT,
  `vendor_id` INT NOT NULL,
  `final_po_number` INT NULL,
  `createdAt` TINYINT NULL,
  `updatedAt` TINYINT NULL,
  PRIMARY KEY (`po`, `user_id`, `job_id`, `vendor_id`),
  INDEX `fk_Purchases_Jobs1_idx` (`vendor_id` ASC),
  UNIQUE INDEX `po_UNIQUE` (`po` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  CONSTRAINT `fk_Purchases_Jobs1`
    FOREIGN KEY (`vendor_id`)
    REFERENCES `usel`.`Jobs` (`job_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Purchases_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `usel`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `usel`.`Vendors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usel`.`Vendors` (
  `id` INT NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `createdAt` TINYINT NULL,
  `updatedAt` TINYINT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Vendors_Purchases`
    FOREIGN KEY (`id`)
    REFERENCES `usel`.`Purchases` (`vendor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `usel`.`Vessels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usel`.`Vessels` (
  `id` INT NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  `createdAt` TINYINT NULL,
  `updatedAt` TINYINT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Vessels_Customers1`
    FOREIGN KEY (`id`)
    REFERENCES `usel`.`Customers` (`vessel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS; 